[package]
name = "trees"
version = "0.1.0"
authors = ["Barry jay <Barry.Jay8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.46"
nom = "6.0.0"
